### ISSUE TITLE
release img.xz 缺少 version

### ISSUE THREAD

**Issue by nihui** [AvaotaSBC/AvaotaOS#3]
AvaotaOS-jammy-cli-arm64-avaota-a1.img.xz 看不出来是什么版本啦
AvaotaOS-jammy-cli-arm64-avaota-a1-v0.2.7.2.img.xz 这样或许更好些

获取tag名字
```
${GITHUB_REF/refs\/tags\//}
```

**Comment by chainsx** [comment]
加啦：

https://github.com/AvaotaSBC/AvaotaOS/commit/1eeefdec8f8737a4ede3da59dbf61edcfff0531d

![tietie](https://raw.githubusercontent.com/chainsx/doc/master/tietie.gif)

**Comment by nihui** [comment]
好耶！

![302F7ED4CDE4B59FC13D9FCC45DC1157 jpg](https://github.com/AvaotaSBC/AvaotaOS/assets/171016/19777125-4788-4be3-b011-3907334603a0)
